version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ${PGADMIN_CONTAINER_NAME}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@admin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
    depends_on:
      - postgres 
    ports:
      - "8000:80"
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    networks:
      - data-network
    env_file:
      - ../.env

  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    hostname: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    volumes:
       - ../sql-1:/sql-1
       - ../sql-2:/sql-2
       - ../data:/data
    networks:
      - data-network
    env_file:
      - ../.env

networks:
  data-network:
    name: data-network
    external: true

volumes:
  pgadmin_data: